#!/bin/sh

INTERFACE="$1"

# Set interface up
/sbin/ip link set $INTERFACE up

# Launch wpa_supplicant in daemon mode
/sbin/wpa_supplicant -B -D nl80211,wext \
		     -c/etc/wpa_supplicant/wpasupplicant.conf\
		     -i$INTERFACE -ddd

# Get the IP from router
/sbin/dhclient $INTERFACE
